select *from hospitality.dim_date;
select *from hospitality.dim_hotels;
select *from hospitality.dim_rooms;
select *from hospitality.fact_aggregated_bookings;
select *from hospitality.fact_bookings;
-- getting the revenue generated by properties
select property_id, revenue_generated from hospitality.fact_bookings;
-- counting the number of successful bookings 
select count(successful_bookings) as Total_bookings from hospitality.fact_aggregated_bookings;
-- number of unsuccessful bookings in two ways
select count(booking_status) as unsuccessfulbooking from hospitality.fact_bookings where booking_status= "Cancelled";
select all(booking_status), count(booking_status) as count from hospitality.fact_bookings where booking_status= "Cancelled";
-- property name with in the luxury category
select distinct(property_name), property_id from hospitality.dim_hotels where category = "Luxury";
-- joining two tables, the hotels and bookings table
select * from hospitality.dim_hotels ppn join hospitality.fact_bookings pp1 on ppn.property_id = pp1.property_id; 
-- properties with successful checkouts
select ppn.property_name, ppn.property_id, pp1.room_category
from hospitality.dim_hotels ppn
join hospitality.fact_bookings pp1
on ppn.property_id = pp1.property_id
where pp1.booking_status = "checked out"; 
-- date with major bookings
select ppn.property_name, pp1.booking_date, pp1.room_category, pp1.ratings_given
from hospitality.dim_hotels ppn
join hospitality.fact_bookings pp1
on ppn.property_id = pp1.property_id
where pp1.booking_status = "checked out" 
and pp1.ratings_given > 4.0
group by pp1.ratings_given, pp1.room_category;
